from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    ForeignKey,
    Float,
    Index,
    func
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.database import Base


class AlertModel(Base):
    """
    SENTRA Threat Alert Entity.
    Stores evidence-backed security alerts generated by the AI/ML detection decision engine.
    """
    __tablename__ = "threat_alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # Associated entities
    flow_id = Column(Integer, ForeignKey("traffic_flows.id", ondelete="SET NULL"), nullable=True, index=True)
    server_id = Column(Integer, ForeignKey("monitored_servers.id", ondelete="SET NULL"), nullable=True, index=True)
    import_id = Column(Integer, ForeignKey("pcap_imports.id", ondelete="SET NULL"), nullable=True, index=True)
    model_id = Column(Integer, ForeignKey("ml_models.id", ondelete="SET NULL"), nullable=True, index=True)
    
    # Threat & Decision classification
    threat = Column(String(100), nullable=False, index=True)
    threat_class = Column(String(100), nullable=False, index=True)
    detection_type = Column(String(50), nullable=False, default="classification")  # classification, anomaly, hybrid_rule
    detection_decision = Column(String(50), nullable=False, default="suspicious")  # likely_malicious, suspicious, anomalous, inconclusive
    severity = Column(String(50), nullable=False, default="medium", index=True)    # low, medium, high, critical
    
    # Numerical model outputs (clearly distinguishing uncalibrated model scores)
    model_score = Column(Float, nullable=True)     # Supervised class score / vote share (0.0 - 1.0)
    anomaly_score = Column(Float, nullable=True)   # Isolation forest decision score (negative = higher isolation)
    
    # Observed 5-tuple network facts
    source_ip = Column(String(64), nullable=False, index=True)
    destination_ip = Column(String(64), nullable=False, index=True)
    source_port = Column(Integer, nullable=True)
    destination_port = Column(Integer, nullable=True, index=True)
    protocol = Column(String(20), nullable=False, default="TCP", index=True)
    
    # Structured evidence: network telemetry, feature values, decision rules, and model parameters
    evidence = Column(JSONB, nullable=False, default=dict)
    
    # Versioning & Traceability
    model_version = Column(String(50), nullable=True)
    feature_schema_version = Column(String(20), nullable=False, default="v1.0.0")
    detection_policy_version = Column(String(20), nullable=False, default="v1.0.0")
    
    # Deduplication & Frequency tracking
    dedup_key = Column(String(128), nullable=True, index=True)
    occurrence_count = Column(Integer, nullable=False, default=1)
    
    # Lifecycle & Timestamps
    status = Column(String(50), nullable=False, default="new", index=True)  # new, acknowledged, investigating, resolved, false_positive
    details = Column(Text, nullable=True)
    
    first_seen_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_seen_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    flow = relationship("TrafficFlowModel", backref="alerts", lazy="joined")
    server = relationship("MonitoredServerModel", backref="alerts", lazy="joined")
    pcap_import = relationship("PcapImportModel", backref="alerts", lazy="joined")
    model = relationship("MLModelModel", backref="alerts", lazy="joined")
    history = relationship("AlertStatusHistoryModel", back_populates="alert", cascade="all, delete-orphan", order_by="desc(AlertStatusHistoryModel.created_at)")

    __table_args__ = (
        Index("ix_threat_alerts_server_severity", "server_id", "severity"),
        Index("ix_threat_alerts_status_severity", "status", "severity"),
        Index("ix_threat_alerts_dedup_status", "dedup_key", "status"),
    )

    def __repr__(self):
        return f"<ThreatAlert(id={self.id}, threat={self.threat_class}, severity={self.severity}, status={self.status})>"


class AlertStatusHistoryModel(Base):
    """
    Audit trail for alert state transitions.
    """
    __tablename__ = "alert_status_history"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    alert_id = Column(Integer, ForeignKey("threat_alerts.id", ondelete="CASCADE"), nullable=False, index=True)
    previous_status = Column(String(50), nullable=False)
    new_status = Column(String(50), nullable=False)
    changed_by = Column(String(100), nullable=False, default="operator")
    note = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    alert = relationship("AlertModel", back_populates="history")

    def __repr__(self):
        return f"<AlertStatusHistory(alert_id={self.alert_id}, {self.previous_status} -> {self.new_status})>"
