"""create monitored_servers table

Revision ID: a8581e7e5387
Revises: 
Create Date: 2026-09-30 14:39:59.547091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8581e7e5387'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('server_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('traffic_source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_servers_id'), 'monitored_servers', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_servers_ip_address'), 'monitored_servers', ['ip_address'], unique=False)
    op.create_index(op.f('ix_monitored_servers_name'), 'monitored_servers', ['name'], unique=False)
    op.create_table('threat_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('threat', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('destination_ip', sa.String(length=64), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('model_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['monitored_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_alerts_id'), 'threat_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_threat_alerts_server_id'), 'threat_alerts', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_alerts_server_id'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_id'), table_name='threat_alerts')
    op.drop_table('threat_alerts')
    op.drop_index(op.f('ix_monitored_servers_name'), table_name='monitored_servers')
    op.drop_index(op.f('ix_monitored_servers_ip_address'), table_name='monitored_servers')
    op.drop_index(op.f('ix_monitored_servers_id'), table_name='monitored_servers')
    op.drop_table('monitored_servers')
    # ### end Alembic commands ###
