"""create pcap_imports and traffic_flows tables

Revision ID: b9add0592189
Revises: a8581e7e5387
Create Date: 2026-10-02 13:54:30.011139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9add0592189'
down_revision: Union[str, Sequence[str], None] = 'a8581e7e5387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcap_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.Column('total_flows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['monitored_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcap_imports_id'), 'pcap_imports', ['id'], unique=False)
    op.create_index(op.f('ix_pcap_imports_server_id'), 'pcap_imports', ['server_id'], unique=False)
    op.create_index(op.f('ix_pcap_imports_status'), 'pcap_imports', ['status'], unique=False)
    op.create_index(op.f('ix_pcap_imports_uploaded_at'), 'pcap_imports', ['uploaded_at'], unique=False)
    op.create_table('traffic_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('destination_ip', sa.String(length=64), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('average_packet_size', sa.Float(), nullable=False),
    sa.Column('packets_per_second', sa.Float(), nullable=False),
    sa.Column('bytes_per_second', sa.Float(), nullable=False),
    sa.Column('average_interarrival_time', sa.Float(), nullable=False),
    sa.Column('tcp_syn_count', sa.Integer(), nullable=False),
    sa.Column('tcp_ack_count', sa.Integer(), nullable=False),
    sa.Column('tcp_fin_count', sa.Integer(), nullable=False),
    sa.Column('tcp_rst_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['pcap_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['monitored_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_flows_destination_ip'), 'traffic_flows', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_traffic_flows_destination_port'), 'traffic_flows', ['destination_port'], unique=False)
    op.create_index('ix_traffic_flows_endpoints', 'traffic_flows', ['source_ip', 'destination_ip'], unique=False)
    op.create_index(op.f('ix_traffic_flows_id'), 'traffic_flows', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_flows_import_id'), 'traffic_flows', ['import_id'], unique=False)
    op.create_index('ix_traffic_flows_ports', 'traffic_flows', ['source_port', 'destination_port'], unique=False)
    op.create_index(op.f('ix_traffic_flows_protocol'), 'traffic_flows', ['protocol'], unique=False)
    op.create_index('ix_traffic_flows_protocol_import', 'traffic_flows', ['import_id', 'protocol'], unique=False)
    op.create_index(op.f('ix_traffic_flows_server_id'), 'traffic_flows', ['server_id'], unique=False)
    op.create_index(op.f('ix_traffic_flows_source_ip'), 'traffic_flows', ['source_ip'], unique=False)
    op.create_index(op.f('ix_traffic_flows_source_port'), 'traffic_flows', ['source_port'], unique=False)
    op.create_index(op.f('ix_traffic_flows_start_time'), 'traffic_flows', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_flows_start_time'), table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_source_port'), table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_source_ip'), table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_server_id'), table_name='traffic_flows')
    op.drop_index('ix_traffic_flows_protocol_import', table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_protocol'), table_name='traffic_flows')
    op.drop_index('ix_traffic_flows_ports', table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_import_id'), table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_id'), table_name='traffic_flows')
    op.drop_index('ix_traffic_flows_endpoints', table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_destination_port'), table_name='traffic_flows')
    op.drop_index(op.f('ix_traffic_flows_destination_ip'), table_name='traffic_flows')
    op.drop_table('traffic_flows')
    op.drop_index(op.f('ix_pcap_imports_uploaded_at'), table_name='pcap_imports')
    op.drop_index(op.f('ix_pcap_imports_status'), table_name='pcap_imports')
    op.drop_index(op.f('ix_pcap_imports_server_id'), table_name='pcap_imports')
    op.drop_index(op.f('ix_pcap_imports_id'), table_name='pcap_imports')
    op.drop_table('pcap_imports')
    # ### end Alembic commands ###
