"""update threat_alerts schema and create detection_jobs and alert_history

Revision ID: d6a851b2ed10
Revises: 79ded9632ce5
Create Date: 2026-10-02 14:53:18.037625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6a851b2ed10'
down_revision: Union[str, Sequence[str], None] = '79ded9632ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('classifier_model_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_model_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('total_flows', sa.Integer(), nullable=False),
    sa.Column('analyzed_flows', sa.Integer(), nullable=False),
    sa.Column('alerts_generated', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classifier_model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['pcap_imports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_jobs_dataset_id'), 'detection_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_id'), 'detection_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_import_id'), 'detection_jobs', ['import_id'], unique=False)
    op.create_index(op.f('ix_detection_jobs_status'), 'detection_jobs', ['status'], unique=False)
    op.create_table('alert_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['threat_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_status_history_alert_id'), 'alert_status_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_status_history_id'), 'alert_status_history', ['id'], unique=False)
    op.add_column('threat_alerts', sa.Column('flow_id', sa.Integer(), nullable=True))
    op.add_column('threat_alerts', sa.Column('import_id', sa.Integer(), nullable=True))
    op.add_column('threat_alerts', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('threat_alerts', sa.Column('threat_class', sa.String(length=100), server_default='Suspicious Traffic', nullable=False))
    op.add_column('threat_alerts', sa.Column('detection_type', sa.String(length=50), server_default='classification', nullable=False))
    op.add_column('threat_alerts', sa.Column('detection_decision', sa.String(length=50), server_default='suspicious', nullable=False))
    op.add_column('threat_alerts', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('threat_alerts', sa.Column('source_port', sa.Integer(), nullable=True))
    op.add_column('threat_alerts', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('threat_alerts', sa.Column('model_version', sa.String(length=50), nullable=True))
    op.add_column('threat_alerts', sa.Column('feature_schema_version', sa.String(length=20), server_default='v1.0.0', nullable=False))
    op.add_column('threat_alerts', sa.Column('detection_policy_version', sa.String(length=20), server_default='v1.0.0', nullable=False))
    op.add_column('threat_alerts', sa.Column('dedup_key', sa.String(length=128), nullable=True))
    op.add_column('threat_alerts', sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False))
    op.add_column('threat_alerts', sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_alerts', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('threat_alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_threat_alerts_created_at'), 'threat_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_threat_alerts_dedup_key'), 'threat_alerts', ['dedup_key'], unique=False)
    op.create_index('ix_threat_alerts_dedup_status', 'threat_alerts', ['dedup_key', 'status'], unique=False)
    op.create_index(op.f('ix_threat_alerts_destination_ip'), 'threat_alerts', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_threat_alerts_destination_port'), 'threat_alerts', ['destination_port'], unique=False)
    op.create_index(op.f('ix_threat_alerts_flow_id'), 'threat_alerts', ['flow_id'], unique=False)
    op.create_index(op.f('ix_threat_alerts_import_id'), 'threat_alerts', ['import_id'], unique=False)
    op.create_index(op.f('ix_threat_alerts_model_id'), 'threat_alerts', ['model_id'], unique=False)
    op.create_index(op.f('ix_threat_alerts_protocol'), 'threat_alerts', ['protocol'], unique=False)
    op.create_index('ix_threat_alerts_server_severity', 'threat_alerts', ['server_id', 'severity'], unique=False)
    op.create_index(op.f('ix_threat_alerts_severity'), 'threat_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_alerts_source_ip'), 'threat_alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_threat_alerts_status'), 'threat_alerts', ['status'], unique=False)
    op.create_index('ix_threat_alerts_status_severity', 'threat_alerts', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_threat_alerts_threat'), 'threat_alerts', ['threat'], unique=False)
    op.create_index(op.f('ix_threat_alerts_threat_class'), 'threat_alerts', ['threat_class'], unique=False)
    op.drop_constraint(op.f('threat_alerts_server_id_fkey'), 'threat_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'threat_alerts', 'traffic_flows', ['flow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_alerts', 'ml_models', ['model_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_alerts', 'pcap_imports', ['import_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'threat_alerts', 'monitored_servers', ['server_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'threat_alerts', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'threat_alerts', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'threat_alerts', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'threat_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('threat_alerts_server_id_fkey'), 'threat_alerts', 'monitored_servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_threat_alerts_threat_class'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_threat'), table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_status_severity', table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_status'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_source_ip'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_severity'), table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_server_severity', table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_protocol'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_model_id'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_import_id'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_flow_id'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_destination_port'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_destination_ip'), table_name='threat_alerts')
    op.drop_index('ix_threat_alerts_dedup_status', table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_dedup_key'), table_name='threat_alerts')
    op.drop_index(op.f('ix_threat_alerts_created_at'), table_name='threat_alerts')
    op.drop_column('threat_alerts', 'updated_at')
    op.drop_column('threat_alerts', 'last_seen_at')
    op.drop_column('threat_alerts', 'first_seen_at')
    op.drop_column('threat_alerts', 'occurrence_count')
    op.drop_column('threat_alerts', 'dedup_key')
    op.drop_column('threat_alerts', 'detection_policy_version')
    op.drop_column('threat_alerts', 'feature_schema_version')
    op.drop_column('threat_alerts', 'model_version')
    op.drop_column('threat_alerts', 'evidence')
    op.drop_column('threat_alerts', 'source_port')
    op.drop_column('threat_alerts', 'anomaly_score')
    op.drop_column('threat_alerts', 'detection_decision')
    op.drop_column('threat_alerts', 'detection_type')
    op.drop_column('threat_alerts', 'threat_class')
    op.drop_column('threat_alerts', 'model_id')
    op.drop_column('threat_alerts', 'import_id')
    op.drop_column('threat_alerts', 'flow_id')
    op.drop_index(op.f('ix_alert_status_history_id'), table_name='alert_status_history')
    op.drop_index(op.f('ix_alert_status_history_alert_id'), table_name='alert_status_history')
    op.drop_table('alert_status_history')
    op.drop_index(op.f('ix_detection_jobs_status'), table_name='detection_jobs')
    op.drop_index(op.f('ix_detection_jobs_import_id'), table_name='detection_jobs')
    op.drop_index(op.f('ix_detection_jobs_id'), table_name='detection_jobs')
    op.drop_index(op.f('ix_detection_jobs_dataset_id'), table_name='detection_jobs')
    op.drop_table('detection_jobs')
    # ### end Alembic commands ###
