"""create feature_jobs, flow_features, and feature_datasets tables

Revision ID: e7feab683916
Revises: b9add0592189
Create Date: 2026-10-02 14:17:01.039466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7feab683916'
down_revision: Union[str, Sequence[str], None] = 'b9add0592189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('input_flows', sa.Integer(), nullable=False),
    sa.Column('valid_flows', sa.Integer(), nullable=False),
    sa.Column('invalid_flows', sa.Integer(), nullable=False),
    sa.Column('generated_features', sa.Integer(), nullable=False),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['pcap_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['monitored_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_jobs_id'), 'feature_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_feature_jobs_import_id'), 'feature_jobs', ['import_id'], unique=False)
    op.create_index(op.f('ix_feature_jobs_schema_version'), 'feature_jobs', ['schema_version'], unique=False)
    op.create_index(op.f('ix_feature_jobs_server_id'), 'feature_jobs', ['server_id'], unique=False)
    op.create_index(op.f('ix_feature_jobs_status'), 'feature_jobs', ['status'], unique=False)
    op.create_table('feature_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['feature_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_datasets_id'), 'feature_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_feature_datasets_job_id'), 'feature_datasets', ['job_id'], unique=False)
    op.create_table('flow_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('feature_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['traffic_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['feature_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_features_flow_id'), 'flow_features', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_features_id'), 'flow_features', ['id'], unique=False)
    op.create_index('ix_flow_features_job_flow', 'flow_features', ['job_id', 'flow_id'], unique=True)
    op.create_index(op.f('ix_flow_features_job_id'), 'flow_features', ['job_id'], unique=False)
    op.create_index(op.f('ix_flow_features_schema_version'), 'flow_features', ['schema_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_features_schema_version'), table_name='flow_features')
    op.drop_index(op.f('ix_flow_features_job_id'), table_name='flow_features')
    op.drop_index('ix_flow_features_job_flow', table_name='flow_features')
    op.drop_index(op.f('ix_flow_features_id'), table_name='flow_features')
    op.drop_index(op.f('ix_flow_features_flow_id'), table_name='flow_features')
    op.drop_table('flow_features')
    op.drop_index(op.f('ix_feature_datasets_job_id'), table_name='feature_datasets')
    op.drop_index(op.f('ix_feature_datasets_id'), table_name='feature_datasets')
    op.drop_table('feature_datasets')
    op.drop_index(op.f('ix_feature_jobs_status'), table_name='feature_jobs')
    op.drop_index(op.f('ix_feature_jobs_server_id'), table_name='feature_jobs')
    op.drop_index(op.f('ix_feature_jobs_schema_version'), table_name='feature_jobs')
    op.drop_index(op.f('ix_feature_jobs_import_id'), table_name='feature_jobs')
    op.drop_index(op.f('ix_feature_jobs_id'), table_name='feature_jobs')
    op.drop_table('feature_jobs')
    # ### end Alembic commands ###
